/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import modul.SessionUser;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//private javax.swing.JTable jTable1;

/**
 *
 * @author attau
 */
public class DashboardUserFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardUserFrame.class.getName());

    /**
     * Creates new form DashboardUserFrame
     */
    public DashboardUserFrame() {
        if (SessionUser.id == 0) {
            new LoginFrame().setVisible(true);
            dispose();
            return;
        }
        initComponents();
        setLocationRelativeTo(null);
        cekRole();
        loadDataUser();
        loadDataHewan();
        instance = this;

        tableDashboardUser.setDefaultEditor(Object.class, null);
        tableDashboardHewan.setDefaultEditor(Object.class, null);
        tableDashboardReservasi.setDefaultEditor(Object.class, null);
        tableDashboardLayanan.setDefaultEditor(Object.class, null);
        jTable5.setDefaultEditor(Object.class, null);
    }
    public static DashboardUserFrame instance;

    public static void refreshHewan() {
        if (instance != null) {
            instance.loadDataHewan();
        }
    }

    private void cekRole() {
        String role = SessionUser.role;
        if (role == null) {
            return;
        }

        switch (role.toLowerCase()) {

            case "staf" -> {
            }

            case "dokter" -> {
                dashboard.remove(dashboardUser);
                dashboard.remove(dashboardHewan);
                dashboard.remove(dashboardLayanan);
                dashboard.remove(riwayatTransaksi);
            }

            case "customer" -> {
                dashboard.remove(dashboardUser);
                dashboard.remove(dashboardHewan);
                dashboard.remove(dahboardReservasi);
                dashboard.remove(dashboardLayanan);
            }
        }
    }

    private void cariUser(String keyword) {

        DefaultTableModel model = (DefaultTableModel) tableDashboardUser.getModel();
        model.setRowCount(0);
        String sql = "SELECT nama, role FROM user WHERE nama LIKE ? OR role LIKE ?";

        try (
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/klinik", "root", ""); PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, "%" + keyword + "%");
            ps.setString(2, "%" + keyword + "%");
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString("nama"), rs.getString("role")});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dashboard = new javax.swing.JTabbedPane();
        dashboardUser = new javax.swing.JPanel();
        tmblCustomer = new javax.swing.JButton();
        btnAdministrasi = new javax.swing.JButton();
        btnDokter = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDashboardUser = new javax.swing.JTable();
        tfCariRoleUser = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        btnManageUser = new javax.swing.JButton();
        dashboardHewan = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDashboardHewan = new javax.swing.JTable();
        tfCariRoleUser1 = new javax.swing.JTextField();
        btnCari1 = new javax.swing.JButton();
        btnManageHewan = new javax.swing.JButton();
        dahboardReservasi = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableDashboardReservasi = new javax.swing.JTable();
        tfCariRoleUser2 = new javax.swing.JTextField();
        btnCari2 = new javax.swing.JButton();
        btnReservasi = new javax.swing.JButton();
        dashboardLayanan = new javax.swing.JPanel();
        btnCustomer3 = new javax.swing.JButton();
        btnAdministrasi3 = new javax.swing.JButton();
        btnDokter3 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableDashboardLayanan = new javax.swing.JTable();
        tfCariRoleUser3 = new javax.swing.JTextField();
        btnCari3 = new javax.swing.JButton();
        btnLayanan = new javax.swing.JButton();
        riwayatTransaksi = new javax.swing.JPanel();
        btnCustomer4 = new javax.swing.JButton();
        btnAdministrasi4 = new javax.swing.JButton();
        btnDokter4 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        tableRiwayatTransaksi = new javax.swing.JTextField();
        btnCari6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tmblLogoutDashboard = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dashboard.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tmblCustomer.setText("Customer");
        tmblCustomer.addActionListener(this::tmblCustomerActionPerformed);

        btnAdministrasi.setText("Administrasi");
        btnAdministrasi.addActionListener(this::btnAdministrasiActionPerformed);

        btnDokter.setText("Dokter");
        btnDokter.addActionListener(this::btnDokterActionPerformed);

        tableDashboardUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Role"
            }
        ));
        jScrollPane1.setViewportView(tableDashboardUser);

        tfCariRoleUser.setText("Cari berdasarkan nama");
        tfCariRoleUser.addActionListener(this::tfCariRoleUserActionPerformed);

        btnCari.setText("Cari");
        btnCari.addActionListener(this::btnCariActionPerformed);

        btnManageUser.setText("Manage User");
        btnManageUser.addActionListener(this::btnManageUserActionPerformed);

        javax.swing.GroupLayout dashboardUserLayout = new javax.swing.GroupLayout(dashboardUser);
        dashboardUser.setLayout(dashboardUserLayout);
        dashboardUserLayout.setHorizontalGroup(
            dashboardUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dashboardUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dashboardUserLayout.createSequentialGroup()
                        .addComponent(tmblCustomer)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdministrasi)
                        .addGap(18, 18, 18)
                        .addComponent(btnDokter)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(dashboardUserLayout.createSequentialGroup()
                        .addComponent(tfCariRoleUser, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCari)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 549, Short.MAX_VALUE)
                        .addComponent(btnManageUser))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 903, Short.MAX_VALUE))
                .addContainerGap())
        );
        dashboardUserLayout.setVerticalGroup(
            dashboardUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dashboardUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCariRoleUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari)
                    .addComponent(btnManageUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dashboardUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tmblCustomer)
                    .addComponent(btnAdministrasi)
                    .addComponent(btnDokter))
                .addGap(162, 162, 162))
        );

        dashboard.addTab("Dashboard User", dashboardUser);

        tableDashboardHewan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Hewan", "Customer"
            }
        ));
        jScrollPane2.setViewportView(tableDashboardHewan);

        tfCariRoleUser1.setText("Cari berdasarkan nama");
        tfCariRoleUser1.addActionListener(this::tfCariRoleUser1ActionPerformed);

        btnCari1.setText("Cari");
        btnCari1.addActionListener(this::btnCari1ActionPerformed);

        btnManageHewan.setText("Manage Hewan");
        btnManageHewan.addActionListener(this::btnManageHewanActionPerformed);

        javax.swing.GroupLayout dashboardHewanLayout = new javax.swing.GroupLayout(dashboardHewan);
        dashboardHewan.setLayout(dashboardHewanLayout);
        dashboardHewanLayout.setHorizontalGroup(
            dashboardHewanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardHewanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dashboardHewanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 903, Short.MAX_VALUE)
                    .addGroup(dashboardHewanLayout.createSequentialGroup()
                        .addComponent(tfCariRoleUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCari1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnManageHewan)))
                .addContainerGap())
        );
        dashboardHewanLayout.setVerticalGroup(
            dashboardHewanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardHewanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dashboardHewanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCariRoleUser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari1)
                    .addComponent(btnManageHewan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        dashboard.addTab("Dashboard Hewan", dashboardHewan);

        tableDashboardReservasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer", "Hewan", "Tipe Layananl"
            }
        ));
        jScrollPane3.setViewportView(tableDashboardReservasi);

        tfCariRoleUser2.setText("Cari berdasarkan nama");

        btnCari2.setText("Cari");

        btnReservasi.setText("Manage Reservasi");
        btnReservasi.addActionListener(this::btnReservasiActionPerformed);

        javax.swing.GroupLayout dahboardReservasiLayout = new javax.swing.GroupLayout(dahboardReservasi);
        dahboardReservasi.setLayout(dahboardReservasiLayout);
        dahboardReservasiLayout.setHorizontalGroup(
            dahboardReservasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dahboardReservasiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dahboardReservasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 903, Short.MAX_VALUE)
                    .addGroup(dahboardReservasiLayout.createSequentialGroup()
                        .addComponent(tfCariRoleUser2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCari2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReservasi)))
                .addContainerGap())
        );
        dahboardReservasiLayout.setVerticalGroup(
            dahboardReservasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dahboardReservasiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dahboardReservasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCariRoleUser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari2)
                    .addComponent(btnReservasi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        dashboard.addTab("Dashboard Reservasi", dahboardReservasi);

        btnCustomer3.setText("Customer");
        btnCustomer3.addActionListener(this::btnCustomer3ActionPerformed);

        btnAdministrasi3.setText("Administrasi");
        btnAdministrasi3.addActionListener(this::btnAdministrasi3ActionPerformed);

        btnDokter3.setText("Dokter");
        btnDokter3.addActionListener(this::btnDokter3ActionPerformed);

        tableDashboardLayanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Layanan", "Harga", "Deskripsi Layanan"
            }
        ));
        jScrollPane4.setViewportView(tableDashboardLayanan);

        tfCariRoleUser3.setText("Cari berdasarkan nama");
        tfCariRoleUser3.addActionListener(this::tfCariRoleUser3ActionPerformed);

        btnCari3.setText("Cari");
        btnCari3.addActionListener(this::btnCari3ActionPerformed);

        btnLayanan.setText("Manage Layanan");
        btnLayanan.addActionListener(this::btnLayananActionPerformed);

        javax.swing.GroupLayout dashboardLayananLayout = new javax.swing.GroupLayout(dashboardLayanan);
        dashboardLayanan.setLayout(dashboardLayananLayout);
        dashboardLayananLayout.setHorizontalGroup(
            dashboardLayananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardLayananLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dashboardLayananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 903, Short.MAX_VALUE)
                    .addGroup(dashboardLayananLayout.createSequentialGroup()
                        .addComponent(btnCustomer3)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdministrasi3)
                        .addGap(18, 18, 18)
                        .addComponent(btnDokter3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(dashboardLayananLayout.createSequentialGroup()
                        .addComponent(tfCariRoleUser3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCari3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLayanan)))
                .addContainerGap())
        );
        dashboardLayananLayout.setVerticalGroup(
            dashboardLayananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardLayananLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dashboardLayananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCariRoleUser3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari3)
                    .addComponent(btnLayanan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(dashboardLayananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCustomer3)
                    .addComponent(btnAdministrasi3)
                    .addComponent(btnDokter3))
                .addGap(162, 162, 162))
        );

        dashboard.addTab("Dashboard Layanan", dashboardLayanan);

        btnCustomer4.setText("Customer");
        btnCustomer4.addActionListener(this::btnCustomer4ActionPerformed);

        btnAdministrasi4.setText("Administrasi");
        btnAdministrasi4.addActionListener(this::btnAdministrasi4ActionPerformed);

        btnDokter4.setText("Dokter");
        btnDokter4.addActionListener(this::btnDokter4ActionPerformed);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Hewan", "Dokter", "Tipe Layanan", "Harga"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        tableRiwayatTransaksi.setText("Cari berdasarkan nama");
        tableRiwayatTransaksi.addActionListener(this::tableRiwayatTransaksiActionPerformed);

        btnCari6.setText("Cari");
        btnCari6.addActionListener(this::btnCari6ActionPerformed);

        javax.swing.GroupLayout riwayatTransaksiLayout = new javax.swing.GroupLayout(riwayatTransaksi);
        riwayatTransaksi.setLayout(riwayatTransaksiLayout);
        riwayatTransaksiLayout.setHorizontalGroup(
            riwayatTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(riwayatTransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(riwayatTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 903, Short.MAX_VALUE)
                    .addGroup(riwayatTransaksiLayout.createSequentialGroup()
                        .addGroup(riwayatTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(riwayatTransaksiLayout.createSequentialGroup()
                                .addComponent(btnCustomer4)
                                .addGap(18, 18, 18)
                                .addComponent(btnAdministrasi4)
                                .addGap(18, 18, 18)
                                .addComponent(btnDokter4))
                            .addGroup(riwayatTransaksiLayout.createSequentialGroup()
                                .addComponent(tableRiwayatTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCari6)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        riwayatTransaksiLayout.setVerticalGroup(
            riwayatTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(riwayatTransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(riwayatTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tableRiwayatTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(riwayatTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCustomer4)
                    .addComponent(btnAdministrasi4)
                    .addComponent(btnDokter4))
                .addGap(162, 162, 162))
        );

        dashboard.addTab("Riwayat Transaksi", riwayatTransaksi);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Dashboard User");

        tmblLogoutDashboard.setText("Logout");
        tmblLogoutDashboard.addActionListener(this::tmblLogoutDashboardActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dashboard)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(385, 385, 385)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tmblLogoutDashboard)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tmblLogoutDashboard))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDokterActionPerformed
        // TODO add your handling code here:
        tfCariRoleUser.setText("dokter");
        cariUser("dokter");
    }//GEN-LAST:event_btnDokterActionPerformed

    private void btnAdministrasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministrasiActionPerformed
        // TODO add your handling code here:
        tfCariRoleUser.setText("staf");
        cariUser("staf");
    }//GEN-LAST:event_btnAdministrasiActionPerformed

    private void btnAdministrasi3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministrasi3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdministrasi3ActionPerformed

    private void btnDokter3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDokter3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDokter3ActionPerformed

    private void btnCustomer3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomer3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCustomer3ActionPerformed

    private void tfCariRoleUser3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCariRoleUser3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCariRoleUser3ActionPerformed

    private void btnCari3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCari3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCari3ActionPerformed

    private void tfCariRoleUser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCariRoleUser1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCariRoleUser1ActionPerformed

    private void btnCari1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCari1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCari1ActionPerformed

    private void tfCariRoleUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCariRoleUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCariRoleUserActionPerformed

    private void btnManageUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageUserActionPerformed
        // TODO add your handling code here:
        ManageUserFrame frame = new ManageUserFrame();
        frame.setLocationRelativeTo(this);
        frame.setVisible(true);
        //loadDataHewan();
        //JOptionPane.showMessageDialog(this,"Data berhasil disimpan");
//        ManageUserFrame dialog = new ManageUserFrame(this, true);
//        dialog.setVisible(true);

    }//GEN-LAST:event_btnManageUserActionPerformed

    private void btnCustomer4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomer4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCustomer4ActionPerformed

    private void btnAdministrasi4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministrasi4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdministrasi4ActionPerformed

    private void btnDokter4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDokter4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDokter4ActionPerformed

    private void tableRiwayatTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableRiwayatTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tableRiwayatTransaksiActionPerformed

    private void btnCari6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCari6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCari6ActionPerformed

    private void tmblLogoutDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmblLogoutDashboardActionPerformed
        // TODO add your handling code here:
        SessionUser.logout();
        new LoginFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tmblLogoutDashboardActionPerformed

    private void btnLayananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLayananActionPerformed
        // TODO add your handling code here:
        ManageLayananFrame frame = new ManageLayananFrame();
        frame.setLocationRelativeTo(this);
        frame.setVisible(true);
    }//GEN-LAST:event_btnLayananActionPerformed

    private void btnManageHewanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageHewanActionPerformed
        // TODO add your handling code here:
        ManageHewanFrame frame = new ManageHewanFrame();
        frame.setLocationRelativeTo(this);
        frame.setVisible(true);

    }//GEN-LAST:event_btnManageHewanActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        String keyword = tfCariRoleUser.getText().trim();
        if (keyword.isEmpty()) {
            loadDataUser();
            return;
        }

        cariUser(keyword);
    }//GEN-LAST:event_btnCariActionPerformed

    private void tmblCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmblCustomerActionPerformed
        // TODO add your handling code here:
        tfCariRoleUser.setText("customer");
        cariUser("customer");
    }//GEN-LAST:event_tmblCustomerActionPerformed

    private void btnReservasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservasiActionPerformed
        // TODO add your handling code here:
        ManageReservasiFrame frame = new ManageReservasiFrame();
        frame.setLocationRelativeTo(this);
        frame.setVisible(true);
    }//GEN-LAST:event_btnReservasiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardUserFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdministrasi;
    private javax.swing.JButton btnAdministrasi3;
    private javax.swing.JButton btnAdministrasi4;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnCari1;
    private javax.swing.JButton btnCari2;
    private javax.swing.JButton btnCari3;
    private javax.swing.JButton btnCari6;
    private javax.swing.JButton btnCustomer3;
    private javax.swing.JButton btnCustomer4;
    private javax.swing.JButton btnDokter;
    private javax.swing.JButton btnDokter3;
    private javax.swing.JButton btnDokter4;
    private javax.swing.JButton btnLayanan;
    private javax.swing.JButton btnManageHewan;
    private javax.swing.JButton btnManageUser;
    private javax.swing.JButton btnReservasi;
    private javax.swing.JPanel dahboardReservasi;
    private javax.swing.JTabbedPane dashboard;
    private javax.swing.JPanel dashboardHewan;
    private javax.swing.JPanel dashboardLayanan;
    private javax.swing.JPanel dashboardUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable5;
    private javax.swing.JPanel riwayatTransaksi;
    private javax.swing.JTable tableDashboardHewan;
    private javax.swing.JTable tableDashboardLayanan;
    private javax.swing.JTable tableDashboardReservasi;
    private javax.swing.JTable tableDashboardUser;
    private javax.swing.JTextField tableRiwayatTransaksi;
    private javax.swing.JTextField tfCariRoleUser;
    private javax.swing.JTextField tfCariRoleUser1;
    private javax.swing.JTextField tfCariRoleUser2;
    private javax.swing.JTextField tfCariRoleUser3;
    private javax.swing.JButton tmblCustomer;
    private javax.swing.JButton tmblLogoutDashboard;
    // End of variables declaration//GEN-END:variables

    private void loadDataUser() {
        DefaultTableModel model = (DefaultTableModel) tableDashboardUser.getModel();

        model.setRowCount(0);
        String sql = "SELECT nama, role FROM user";

        try (
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/klinik", "root", ""); Statement st = conn.createStatement(); ResultSet rs = st.executeQuery(sql)) {
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("nama"),
                    rs.getString("role")});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void loadDataHewan() {
        DefaultTableModel model = (DefaultTableModel) tableDashboardHewan.getModel();
        model.setRowCount(0);

        String sql
                = "SELECT h.nama_hewan, u.nama AS customer "
                + "FROM hewan h JOIN user u ON h.id_customer = u.id_user";

        try (Connection conn = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/klinik",
                "root", ""); PreparedStatement ps = conn.prepareStatement(sql); ResultSet rs = ps.executeQuery()) {

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("nama_hewan"),
                    rs.getString("customer")
                });
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
}
